### ISSUE TITLE
SIG Software Supply Chain Co-chair Nominations

### ISSUE THREAD

**Issue by fdegir** [cdfoundation/sig-software-supply-chain#26]
The Software Supply Chain SIG is now opening elections for a new co-chair!

The process will be quite lightweight. Over the next two weeks, please express your interest in becoming the new co-chair of the Software Supply Chain SIG directly under this issue. You may also nominate someone else to be co-chair of the Software Supply Chain SIG but please make sure to check with that person privately before nominating them.

Please include:
* Name of the candidate
* Their short bio and statement of intent on why they would hold the position
* Any other relevant Information

The nomination period will end on Thursday, December 22, 2022.
If we have multiple interested individuals, we will then hold a vote.

**Comment by bendory** [comment]
🙋🏾 I volunteer.

**Brief bio:**
- Currently Google Engineering Manager for [Tekton](https://tekton.dev/), a graduated project in the CDF portfolio
- Previously Eng Manager for [Google Cloud Build](https://cloud.google.com/build)
- Extensive prior life experience at Goldman Sachs in a variety of roles, including infrastructure and platform engineering and supply chain audits for regulatory compliance

**Statement of intent:** my goals in co-chairing the SIG include:
- deepening and broadening participation across companies and teams
- finding areas of OSS collaboration where even competitors can meet and cooperate to the benefit of our industry and the OSS community
- recruiting one or more demos for each session, where practitioners share products and feature developments, whether in OSS or in vendor offerings

Relevant **Supply Chain SIG participation and contributions**:
- Established the [Supply Chain Maturity Model Workstream](https://github.com/cdfoundation/sig-software-supply-chain/tree/main/workstreams/scmm) under the Supply Chain SIG
- I've attended 4 of the 5 SIG meetings since starting my current role in Tekton, including [presenting at one meeting](https://hackmd.io/MX4W9EE0RBeO3xfJ9wDi_Q?view#Agenda-and-Notes5) and recruiting a [Tekton presentation](https://hackmd.io/MX4W9EE0RBeO3xfJ9wDi_Q?view#Agenda-and-Notes1) at another.

**Comment by fdegir** [comment]
David Bendory of Google has been unopposed for the position and becomes the new co-chair to the SIG Software Supply Chain.

Thanks a lot for volunteering David!

[A pull request](https://github.com/cdfoundation/sig-software-supply-chain/pull/27) is opened to update the readme.
